version: '3.3'

services:
 mariadb_service:
  build: ./requirements/mariadb/
  container_name: mariadb
  restart: always
  networks:
   - inception_net
  ports:
   - "3306:3306"
  volumes:
   - db_vol:/var/lib/mysql
  env_file: .env

 nginx_service:
  build: ./requirements/nginx/
  container_name: nginx
  restart: always
  depends_on:
   - wordpress_service
  ports:
   - "443:443"
  networks:
   - inception_net
  volumes:
   - wp_vol:/var/www

 wordpress_service:
  build: ./requirements/wordpress/
  container_name: wordpress
  depends_on:
   - mariadb_service
  restart: always
  networks:
   - inception_net
  volumes:
   - wp_vol:/var/www
  env_file: .env

networks:
 inception_net:

volumes:
 wp_vol:
  driver: local
  driver_opts:
   type: 'none'
   o: 'bind'
   device: '/home/bekram/data/wp'
 
 db_vol:
  driver: local
  driver_opts:
   type: 'none'
   o: 'bind'
   device: '/home/bekram/data/db'

